maps/urls.py
from django.urls import path

from . import views

app_name = "maps"
urlpatterns = [
    path("", views.pizzeria_map_view, name="map-index"),
]

pizza/urls.py
from django.views.generic import TemplateView
from django.urls import path

from . import views

app_name = "pizza"
urlpatterns = [
    path(
        "about",
        TemplateView.as_view(template_name="pizza/base_about.html"),
        name="about",
    ),
    path("", views.index_view, name="index"),
    path("city-guide/<slug:slug>/", views.city_guide_view, name="city-guide"),
    path("search", views.index_search_view, name="index-search"),
    path("my/favorites", views.FavoritesListView.as_view(), name="favorites-list"),
    path("my/visits", views.PizzeriaVisitListView.as_view(), name="visits-list"),
    path("my/wishlist", views.WishlistListView.as_view(), name="wishlist-list"),
    path("my/ratings", views.RatingsListView.as_view(), name="ratings-list"),
    path("my/reviews", views.ReviewsListView.as_view(), name="reviews-list"),
    path("pizzeria/<int:pk>", views.pizzeria_detail_view, name="pizzeria-detail"),
    path(
        "pizzeria/<int:pizzeria_id>/toggle-wishlist",
        views.toggle_wishlist,
        name="toggle-wishlist",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/toggle-favorite",
        views.toggle_favorite,
        name="toggle-favorite",
    ),
    path("pizzeria/<int:pizzeria_id>/add-visit", views.add_visit, name="add-visit"),
    path(
        "pizzeria/<int:pizzeria_id>/rate/<int:rating_value>",
        views.rate,
        name="rate",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/rate-delete",
        views.rate_delete,
        name="rate-delete",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/review-form",
        views.review_form_view,
        name="review-form",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/delete-review",
        views.delete_review_view,
        name="delete-review",
    ),
]

pizzaRatings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pizza.urls")),
    path("map/", include("maps.urls")),
    path("contact-us/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizza/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models.functions import Coalesce, Lower
from django.db.models import Q
from base.models import City


MIN_RATING = 1
MAX_RATING = 8


class PizzaCategory(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        constraints = [
            models.UniqueConstraint(Lower("name"), name="unique_pizza_category")
        ]
        ordering = ["name"]


class Pizzeria(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    pizza_categories = models.ManyToManyField(PizzaCategory)
    profile_picture = models.ImageField(
        default="default_pizzeria.jpg",
        upload_to="pizzeria_profile_pictures/",
        blank=True,
    )
    address = models.CharField(max_length=255)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    hot_slice = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} in {self.address}"

    class Meta:
        constraints = [
            models.UniqueConstraint(Lower("name"), "address", name="unique_pizzeria")
        ]
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("pizza:pizzeria-detail", kwargs={"pk": self.pk})

    @property
    def rating_count(self):
        return self.rating_set.count()

    @property
    def average_rating(self):
        avg_rating = self.rating_set.aggregate(
            avg=Coalesce(
                models.Avg("rating"), models.Value(0), output_field=models.FloatField()
            )
        )["avg"]

        return round(avg_rating, 1)


class PizzeriaVisit(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pizzeria = models.ForeignKey(Pizzeria, on_delete=models.CASCADE)
    visit_date = models.DateField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "pizzeria", "visit_date"], name="unique_pizzeria_visit"
            )
        ]
        ordering = ["-visit_date"]


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pizzeria = models.ForeignKey(Pizzeria, on_delete=models.CASCADE)
    review_text = models.CharField(max_length=255)
    last_update = models.DateField(auto_now=True)
    create_date = models.DateField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "pizzeria"], name="unique_review")
        ]
        ordering = ["-last_update"]


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pizzeria = models.ForeignKey(Pizzeria, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "pizzeria"], name="unique_wishlist")
        ]
        ordering = ["-create_date"]


class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pizzeria = models.ForeignKey(Pizzeria, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "pizzeria"], name="unique_favorite")
        ]
        ordering = ["-create_date"]


class Rating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pizzeria = models.ForeignKey(Pizzeria, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(MIN_RATING), MaxValueValidator(MAX_RATING)]
    )
    last_update = models.DateField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "pizzeria"], name="unique_rating"),
            models.CheckConstraint(
                check=Q(rating__gte=MIN_RATING) & Q(rating__lte=MAX_RATING),
                name="rating_range_check",
            ),
        ]
        ordering = ["-last_update"]

pizza/views.py
from django.views.decorators.http import require_POST, require_GET
from django.http import HttpResponse
from django.views.generic import ListView
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q

from .models import (
    Pizzeria,
    PizzeriaVisit,
    Wishlist,
    Favorite,
    Review,
    Rating,
    MIN_RATING,
    MAX_RATING,
)
from base.models import City


# LIST VIEWS

PAGINATION_N = 10


@require_GET
def index_view(request):
    context = {
        "milan_pizzerias": Pizzeria.objects.filter(city__name="Milan", hot_slice=True)[
            :4
        ]
    }
    return render(request, "pizza/base_index.html", context)


@require_GET
def index_search_view(request):
    query = request.GET.get("q", "").strip()
    if not query:
        return redirect("pizza:index")

    pizzeria_list = Pizzeria.objects.filter(
        Q(name__icontains=query) | Q(address__icontains=query)
    )
    paginator = Paginator(pizzeria_list, PAGINATION_N)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request, "pizza/base_search.html", {"page_obj": page_obj, "query": query}
    )


@require_GET
def city_guide_view(request, slug: str):
    city: City = get_object_or_404(City, slug=slug)
    context: dict = {
        "pizzerias": Pizzeria.objects.filter(city=city),
        "city": city,
    }
    return render(request, "pizza/base_city_guide.html", context)


class PizzeriaVisitListView(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION_N
    template_name = "pizza/base_personal_pizzeria_list.html"
    http_method_names = ["get"]

    def get_queryset(self):
        return PizzeriaVisit.objects.filter(user=self.request.user)


class WishlistListView(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION_N
    template_name = "pizza/base_personal_pizzeria_list.html"
    http_method_names = ["get"]

    def get_queryset(self):
        return Wishlist.objects.filter(user=self.request.user)


class FavoritesListView(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION_N
    template_name = "pizza/base_personal_pizzeria_list.html"
    http_method_names = ["get"]

    def get_queryset(self):
        return Favorite.objects.filter(user=self.request.user)


class RatingsListView(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION_N
    template_name = "pizza/base_personal_pizzeria_list.html"
    http_method_names = ["get"]

    def get_queryset(self):
        return Rating.objects.filter(user=self.request.user)


class ReviewsListView(LoginRequiredMixin, ListView):
    paginate_by = PAGINATION_N
    template_name = "pizza/base_personal_pizzeria_list.html"
    http_method_names = ["get"]

    def get_queryset(self):
        return Review.objects.filter(user=self.request.user)


# PIZZERIA DETAIL VIEW


def _get_rating_context(rating=None):
    return {
        "rating_value": rating.rating if rating else 0,
        "rating_list": range(MIN_RATING, MAX_RATING + 1),
    }


@require_GET
def pizzeria_detail_view(request, pk):
    pizzeria = get_object_or_404(Pizzeria, pk=pk)
    context = {"pizzeria": pizzeria}

    if request.user.is_authenticated:
        user_visits = PizzeriaVisit.objects.filter(user=request.user, pizzeria=pizzeria)
        context["user_visits"] = user_visits
        context["has_visited_today"] = user_visits.filter(
            visit_date=timezone.now().date()
        ).exists()

        context["has_wishlist"] = Wishlist.objects.filter(
            user=request.user, pizzeria=pizzeria
        ).exists()
        context["is_favorite"] = Favorite.objects.filter(
            user=request.user, pizzeria=pizzeria
        ).exists()
        context["review"] = Review.objects.filter(
            user=request.user, pizzeria=pizzeria
        ).first()

        context.update(
            _get_rating_context(
                Rating.objects.filter(user=request.user, pizzeria=pizzeria).first()
            )
        )
    return render(request, "pizza/base_pizzeria.html", context)


# ACTIONS


@login_required
@require_POST
def toggle_wishlist(request, pizzeria_id):
    pizzeria = get_object_or_404(Pizzeria, pk=pizzeria_id)

    wishlist_item, created = Wishlist.objects.get_or_create(
        user=request.user, pizzeria=pizzeria
    )
    if not created:
        wishlist_item.delete()

    return render(
        request,
        "pizza/base_pizzeria_wishlist.html",
        {"pizzeria": pizzeria, "has_wishlist": created},
    )


@login_required
@require_POST
def toggle_favorite(request, pizzeria_id):
    pizzeria = get_object_or_404(Pizzeria, pk=pizzeria_id)

    favorite_item, created = Favorite.objects.get_or_create(
        user=request.user, pizzeria=pizzeria
    )
    if not created:
        favorite_item.delete()

    return render(
        request,
        "pizza/base_pizzeria_favorite.html",
        {"pizzeria": pizzeria, "is_favorite": created},
    )


@login_required
@require_POST
def add_visit(request, pizzeria_id):
    pizzeria = get_object_or_404(Pizzeria, pk=pizzeria_id)

    visit_date = timezone.now().date()
    if not PizzeriaVisit.objects.filter(
        user=request.user, pizzeria=pizzeria, visit_date=visit_date
    ).exists():
        PizzeriaVisit.objects.create(
            user=request.user, pizzeria=pizzeria, visit_date=visit_date
        )

    return HttpResponse("<p>You have successfully tracked your visit today!</p>")


@login_required
@require_POST
def rate(request, pizzeria_id, rating_value):
    pizzeria = get_object_or_404(Pizzeria, pk=pizzeria_id)

    rating, _ = Rating.objects.get_or_create(
        user=request.user, pizzeria=pizzeria, defaults={"rating": rating_value}
    )
    rating.rating = rating_value
    rating.save()

    context = {"pizzeria": pizzeria}
    context.update(_get_rating_context(rating))

    return render(request, "pizza/base_pizzeria_ratings.html", context)


@login_required
@require_POST
def rate_delete(request, pizzeria_id):
    # TODO: Handle all the 404s gracefully.
    pizzeria = get_object_or_404(Pizzeria, pk=pizzeria_id)
    if rating := Rating.objects.filter(user=request.user, pizzeria=pizzeria).first():
        rating.delete()

    context = {"pizzeria": pizzeria}
    context.update(_get_rating_context())

    return render(request, "pizza/base_pizzeria_ratings.html", context)


@login_required
def review_form_view(request, pizzeria_id):
    pizzeria = get_object_or_404(Pizzeria, pk=pizzeria_id)
    review = Review.objects.filter(user=request.user, pizzeria=pizzeria).first()
    context = {"pizzeria": pizzeria}

    if request.method == "POST" and (review_text := request.POST.get("review_text")):
        if review:
            review.review_text = review_text
            review.save()
        else:
            review = Review.objects.create(
                user=request.user, pizzeria=pizzeria, review_text=review_text
            )
        context["submitted"] = True
    context["review"] = review

    return render(request, "pizza/base_pizzeria_review_section.html", context)


@login_required
def delete_review_view(request, pizzeria_id):
    pizzeria = get_object_or_404(Pizzeria, pk=pizzeria_id)
    if review := Review.objects.filter(user=request.user, pizzeria=pizzeria).first():
        review.delete()

    context = {"pizzeria": pizzeria}
    return render(request, "pizza/base_pizzeria_review_section.html", context)

pizza/templates/pizza/base_about.html
{% extends "base.html" %}
{% block title %}: About{% endblock %}
{% block description %}Learn more about us!{% endblock %}
{% block content %}
<div class="accordion accordion-flush" id="accordionAbout">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button
                class="accordion-button"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseOne"
                aria-expanded="true"
                aria-controls="flush-collapseOne"
            >
                About Us
            </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionAbout">
            <div class="accordion-body">
                Welcome to <span class="fw-bold">Pizzalista</span>—your go-to platform for discovering and sharing everything
                about pizza. Whether you're a casual pizza fan or a connoisseur on the hunt for the best slice, our app
                is designed to bring pizza lovers together in a fun, social, and engaging way.
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseTwo"
                aria-expanded="false"
                aria-controls="flush-collapseTwo"
            >
                Our Vision
            </button>
        </h2>
        <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionAbout">
            <div class="accordion-body">
                We believe pizza is more than just food—it’s a cultural experience that brings people together.
                That’s why we built Pizzalista, a platform where everyone from the casual eater to the seasoned critic
                can find their passion. We want to be the go-to social network for pizza lovers, helping people
                discover, rate, and enjoy the best pizza around the world.
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button
                class="accordion-button collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#flush-collapseThree"
                aria-expanded="false"
                aria-controls="flush-collapseThree"
            >
                What Can I Do on Pizzalista?
            </button>
        </h2>
        <div id="flush-collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionAbout">
            <div class="accordion-body">
                <p class="pb-2">At Pizzalista, you can enhance your pizza experience by:</p>
                <p><span class="fw-bold">Creating a Wishlist:</span> Save pizzerias you want to visit in one easy-to-access list, so you’re always ready for your next pizza adventure.</p>
                <p><span class="fw-bold">Rating Pizzerias:</span> Share your thoughts by scoring your pizza experiences.</p>
                <p><span class="fw-bold">Logging your Visits:</span> Keep track of every pizzeria you've visited.</p>
                <p><span class="fw-bold">Saving your Favourites:</span> Save your favorite pizzerias for easy access later.</p>
                <h3 class="pt-3">Join us and become part of a community of pizza lovers!</h3>
            </div>
        </div>
    </div>
    <p class="pt-5 text-center">
        This website is made with lots of love (for pizza) from <a href="mailto:kon.paschopoulos@gmail.com">Konstantinos Paschopoulos</a>.
    </p>
</div>
{% endblock %}

pizza/templates/pizza/base_city_guide.html
{% extends "base.html" %}
{% block title %}: {{ city }}{% endblock %}
{% block description %}Find the best pizzerias in {{ city }}{% endblock %}
{% block content %}
<div class="d-flex justify-content-center align-items-center bg-light" style="height: 20vh;">
    <div class="text-center">
        <h1>Browse pizzerias in <span class="fw-bold pizza-bg text-white p-1">{{ city }}</span></h1>
    </div>
</div>
<div class="row">
    {% for pizzeria in pizzerias %}
        <div class="col-md-4 pt-3">
            {% include "pizza/pizzeria_image_thumbnail.html" %}
        </div>

        {% if forloop.counter|divisibleby:3 and not forloop.last %}
            </div><div class="row">
        {% endif %}
    {% empty %}
        <p>Sorry, no pizzerias have been uploaded for this city.</p>
    {% endfor %}
</div>
{% endblock %}

pizza/templates/pizza/base_index.html
{% extends "base.html" %}

{% block pre-content %}
<div class="d-flex justify-content-center align-items-center position-relative" style="height: 50vh;">
    {% include "pizza/pizza_icon.svg" %}
    {% include "pizza/pizza_icon.svg" %}
    {% include "pizza/pizza_icon.svg" %}
    <div class="text-center">
        <h1 class="fw-bold pb-1">PIZZALISTA</h1>
        <p class="h3 p-5">Discover, rate, and celebrate your love for pizza<br/>with a global community of <span class="pizza-bg-underline">pizza lovers</span></p>
        {% if not user.is_authenticated %}
            <a
                class="btn btn-primary border-0 pizza-bg text-white fw-bold rounded-0 fs-3"
                aria-label="Login button"
                href="{% url 'account_login' %}"
            >
                GET STARTED
            </a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block content %}
<p class="h3 pt-4">Hot Slices in Milan</p>
<div class="row">
    {% for pizzeria in milan_pizzerias %}
        <div class="col-md-3 pt-3">
            {% include "pizza/pizzeria_image_thumbnail.html" %}
        </div>
    {% endfor %}
</div>
{% endblock %}

pizza/templates/pizza/base_pizzeria_favorite.html
<button
    hx-post="{% url 'pizza:toggle-favorite' pizzeria.id %}"
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-swap="outerHTML"
    hx-disabled-elt="this"
    class="btn btn-light"
    aria-label="Favorite button">
        {% if is_favorite %}
            <span class="text-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                </svg>
            </span>
        {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
            </svg>
        {% endif %}
</button>

pizza/templates/pizza/base_pizzeria_previous_visits.html
{% if not has_visited_today %}
    <div class="d-flex justify-content-center pb-3">
        <button
        hx-post="{% url 'pizza:add-visit' pizzeria.id %}"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        hx-swap="outerHTML"
        hx-disabled-elt="this"
        class="btn btn-outline-success">
            I visited {{ pizzeria.name }} today!
        </button>
    </div>
{% endif %}
{% if user_visits %}
    <div class="fw-bold text-center">Previous visits</div>
    <div class="list-group list-group-flush">
        {% for visit in user_visits %}
            <div class="list-group-item d-flex justify-content-center">
                <div class="pe-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-event" viewBox="0 0 16 16">
                        <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5z"/>
                        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
                    </svg>
                </div>
                <div>{{ visit.visit_date }}</div>
            </div>
        {% endfor %}
    </div>
{% endif %}

pizza/templates/pizza/base_pizzeria_ratings.html
<div id="rating-div">
    <div class="text-center">
        <div><span class="fw-bold">{{ pizzeria.average_rating }}</span> / 8</div>
        <div>{{ pizzeria.rating_count }} ratings</div>
    </div>
    {% if user.is_authenticated %}
        <div class="text-center pt-3">
            {% for i in rating_list %}
                <span
                    class="pizza-star"
                    style="cursor: pointer;{% if i > rating_value %} opacity: 0.5;{% endif %}"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-post="{% url 'pizza:rate' pizzeria.id i %}"
                    hx-target="#rating-div"
                    hx-swap="outerHTML"
                    hx-disabled-elt="this"
                >
                    &#x1f355;
                </span>
            {% endfor %}
            <span
                hx-post="{% url 'pizza:rate-delete' pizzeria.id %}"
                hx-target="#rating-div"
                hx-swap="outerHTML"
                hx-disabled-elt="this"
                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
                </svg>
            </span>
            <p>Your rating</p>
        </div>
    {% endif %}
</div>

pizza/templates/pizza/base_pizzeria_review_section.html
<form hx-post="{% url 'pizza:review-form' pizzeria.id %}" hx-swap="outerHTML" id="review-form" hx-disabled-elt="textarea, button.btn-primary, button.btn-danger">
    {% csrf_token %}

    <div class="form-floating pb-2">
        <textarea class="form-control" placeholder="Leave a private review here" id="floatingTextarea" name="review_text" required>{{ review.review_text }}</textarea>
        <label for="floatingTextarea">Your private review</label>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <button
        hx-post="{% url 'pizza:delete-review' pizzeria.id %}"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        hx-swap="outerHTML"
        hx-target="#review-form"
        hx-disabled-elt="textarea, button.btn-primary, button.btn-danger"
        class="btn btn-danger"
    >
        Delete
    </button>

    {% if submitted %}
        <div class="alert alert-success alert-dismissible fade show mt-2" role="alert">
            Submitted!
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
</form>

pizza/templates/pizza/base_pizzeria_wishlist.html
<button
    hx-post="{% url 'pizza:toggle-wishlist' pizzeria.id %}"
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    hx-swap="outerHTML"
    hx-disabled-elt="this"
    class="btn btn-light"
    aria-label="Wishlist button">
        {% if has_wishlist %}
            <span class="text-success ">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z"/>
                </svg>
            </span>
        {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
            </svg>
        {% endif %}
</button>

pizza/templates/pizza/pizzeria_image_thumbnail.html
<div class="card text-white text-center border-0">
    <img src="{{ pizzeria.profile_picture.url }}" class="card-img pizzeria-img-text-center rounded-0" alt="{{ pizzeria.name }} image" loading="lazy">
    <div class="card-img-overlay d-flex justify-content-center align-items-center">
        <a href="{{ pizzeria.get_absolute_url }}" class="stretched-link text-reset text-decoration-none pizzeria-img-text-center-title">
            <p class="fw-bold fs-4">{{ pizzeria.name }}</p>
            <p>{{ pizzeria.address }}</p>
        </a>
    </div>
</div>