maps/urls.py
from django.urls import path

from . import views

app_name = "maps"
urlpatterns = [
    path("", views.pizzeria_map_view, name="map-index"),
]

pizza/urls.py
from django.views.generic import TemplateView
from django.urls import path

from . import views

app_name = "pizza"
urlpatterns = [
    path(
        "about",
        TemplateView.as_view(template_name="pizza/base_about.html"),
        name="about",
    ),
    path("", views.index_view, name="index"),
    path("city-guide/<slug:slug>/", views.city_guide_view, name="city-guide"),
    path("search", views.index_search_view, name="index-search"),
    path("my/favorites", views.FavoritesListView.as_view(), name="favorites-list"),
    path("my/visits", views.PizzeriaVisitListView.as_view(), name="visits-list"),
    path("my/wishlist", views.WishlistListView.as_view(), name="wishlist-list"),
    path("my/ratings", views.RatingsListView.as_view(), name="ratings-list"),
    path("my/reviews", views.ReviewsListView.as_view(), name="reviews-list"),
    path("pizzeria/<int:pk>", views.pizzeria_detail_view, name="pizzeria-detail"),
    path(
        "pizzeria/<int:pizzeria_id>/toggle-wishlist",
        views.toggle_wishlist,
        name="toggle-wishlist",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/toggle-favorite",
        views.toggle_favorite,
        name="toggle-favorite",
    ),
    path("pizzeria/<int:pizzeria_id>/add-visit", views.add_visit, name="add-visit"),
    path(
        "pizzeria/<int:pizzeria_id>/rate/<int:rating_value>",
        views.rate,
        name="rate",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/rate-delete",
        views.rate_delete,
        name="rate-delete",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/review-form",
        views.review_form_view,
        name="review-form",
    ),
    path(
        "pizzeria/<int:pizzeria_id>/delete-review",
        views.delete_review_view,
        name="delete-review",
    ),
]

pizzaRatings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pizza.urls")),
    path("map/", include("maps.urls")),
    path("contact-us/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.contact_us, name="contact-us"),
]

base/models.py
from django.db import models
from django.db.models.functions import Lower
from django.utils.text import slugify


class Country(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        constraints = [
            models.UniqueConstraint(Lower("name"), name="country_unique_lower_name")
        ]
        ordering = ["name"]

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    header_image = models.ImageField(upload_to="city_images/", blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                Lower("name"), "country", name="city_unique_lower_name_country"
            )
        ]
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}, {self.country.name}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.name}-{self.country.name}")
        super().save(*args, **kwargs)

templates/429.html
{% extends "base.html" %}
{% block content %}
    <h1 class="text-center text-danger">You are sending too many requests.</h1>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="{% block description %}Discover the best pizza in the world with ratings from real pizza lovers. Explore top pizzerias and enjoy authentic flavors.{% endblock %}">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>&#x1f355;</text></svg>">

    <title>Pizzalista{% block title %}{% endblock %}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">Pizzalista</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            City Guides
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'pizza:city-guide' 'milan-italy' %}">Milan</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'maps:map-index' %}">Map</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pizza:about' %}">About</a>
                    </li>
                </ul>
                <form class="d-flex w-100" role="search" method="GET" action="{% url 'pizza:index-search' %}">
                    <div class="input-group">
                        <input id="search-input" value="{{ query }}" name="q" type="search" class="form-control rounded-0" placeholder="Search for pizzerias..." aria-label="Search for pizzerias...">
                        <button class="btn btn-outline-secondary" type="submit" id="search-button" aria-labelledby="search-input">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                            </svg>
                        </button>
                    </div>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:contact-us' %}" style="white-space: nowrap;">Contact Us</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'pizza:wishlist-list' %}">Wishlist</a></li>
                                <li><a class="dropdown-item" href="{% url 'pizza:favorites-list' %}">Favorites</a></li>
                                <li><a class="dropdown-item" href="{% url 'pizza:visits-list' %}">Visits</a></li>
                                <li><a class="dropdown-item" href="{% url 'pizza:ratings-list' %}">Ratings</a></li>
                                <li><a class="dropdown-item" href="{% url 'pizza:reviews-list' %}">Reviews</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'account_set_password' %}">Change Password</a></li>
                                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block pre-content %}{% endblock %}
    <div class="container pt-3">
        {% block content %}{% endblock %}
    </div>
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" defer></script>
</body>
</html>